
[build]
  command = "pnpm run build && node ./scripts/move-export-to-subdir.js"
  publish = "out"

# Ensure the official Netlify plugin for Next.js is used
[[plugins]]
  package = "@netlify/plugin-nextjs"
